# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run unit tests
      run: xcodebuild -scheme Refactoring test -testPlan UnitTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15"
    - name: Run snapshot tests
      run: xcodebuild -scheme Refactoring test -testPlan SnapshotTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15"
